"""Add whitelist grant fields to Invite model

Revision ID: 075ba14cc5a5
Revises: 3c43c7dd77e0
Create Date: 2025-06-29 15:26:56.324117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075ba14cc5a5'
down_revision = '3c43c7dd77e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grant_purge_whitelist', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('grant_bot_whitelist', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_column('grant_bot_whitelist')
        batch_op.drop_column('grant_purge_whitelist')

    # ### end Alembic commands ###
