"""Initial database schema with all tables

Revision ID: 20df17aabd76
Revises: 
Create Date: 2025-05-25 14:47:08.622241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20df17aabd76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
        sa.Column('id', sa.VARCHAR(191), nullable=False),
        sa.Column('next_run_time', sa.FLOAT(precision=53), nullable=True),
        sa.Column('job_state', sa.BLOB(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('app_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_setting_key'), ['key'], unique=True)

    op.create_table('history_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('plex_username', sa.String(length=80), nullable=True),
    sa.Column('discord_id', sa.String(length=80), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('invite_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_path', sa.String(length=80), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=True),
    sa.Column('allowed_libraries', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_link_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_link_custom_path'), ['custom_path'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('plex_thumb_url', sa.String(length=255), nullable=True),
    sa.Column('plex_user_id', sa.Integer(), nullable=True),
    sa.Column('plex_username', sa.String(length=80), nullable=True),
    sa.Column('plex_email', sa.String(length=120), nullable=True),
    sa.Column('discord_id', sa.String(length=80), nullable=True),
    sa.Column('discord_username', sa.String(length=100), nullable=True),
    sa.Column('last_streamed_at', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('invite_link_id', sa.Integer(), nullable=True),
    sa.Column('shares_back', sa.Boolean(), nullable=False),
    sa.Column('is_plex_home_user', sa.Boolean(), nullable=False),
    sa.Column('is_purge_whitelisted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invite_link_id'], ['invite_link.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plex_user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_discord_id'), ['discord_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_plex_email'), ['plex_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_plex_username'), ['plex_username'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_plex_username'))
        batch_op.drop_index(batch_op.f('ix_user_plex_email'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_discord_id'))

    op.drop_table('user')
    with op.batch_alter_table('invite_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_link_custom_path'))
        batch_op.drop_index(batch_op.f('ix_invite_link_created_at'))

    op.drop_table('invite_link')
    with op.batch_alter_table('history_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_history_log_event_type'))

    op.drop_table('history_log')
    with op.batch_alter_table('app_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_setting_key'))

    op.drop_table('app_setting')
    # ### end Alembic commands ###
