"""Add Discord override fields to Invite model

Revision ID: 3c43c7dd77e0
Revises: d2d6805f28ce
Create Date: 2025-06-27 23:42:18.801610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c43c7dd77e0'
down_revision = 'd2d6805f28ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_discord_auth', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('force_guild_membership', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_column('force_guild_membership')
        batch_op.drop_column('force_discord_auth')

    # ### end Alembic commands ###
