"""Add download and transcode permissions to User model

Revision ID: 3d22fcd04e1b
Revises: 47a9200cd541
Create Date: 2025-07-08 22:31:18.481141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d22fcd04e1b'
down_revision = '47a9200cd541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_downloads', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('allow_4k_transcode', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('allow_4k_transcode')
        batch_op.drop_column('allow_downloads')

    # ### end Alembic commands ###
