"""Add StreamHistory model

Revision ID: 47a9200cd541
Revises: 37b77111a573
Create Date: 2025-07-07 07:47:24.774581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a9200cd541'
down_revision = '37b77111a573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(length=255), nullable=True),
    sa.Column('rating_key', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=255), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('player', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_lan', sa.Boolean(), nullable=True),
    sa.Column('media_title', sa.String(length=255), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('grandparent_title', sa.String(length=255), nullable=True),
    sa.Column('parent_title', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stream_history')
    # ### end Alembic commands ###
