"""Add bot and purge whitelist fields to User model

Revision ID: 4fb2e3be9c82
Revises: e10797c88c70 # Should be the ID of your previous successful migration
Create Date: ...

"""
from alembic import op
import sqlalchemy as sa
# No need for app.models imports here as this migration only adds/alters columns
# The types (Boolean, etc.) are standard SQLAlchemy.


# revision identifiers, used by Alembic.
revision = '4fb2e3be9c82'
down_revision = 'e10797c88c70' # Points to your previous successful migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_usages', schema=None) as batch_op:
        batch_op.alter_column('plex_auth_successful',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.false()) # Explicitly set server_default for existing cols
        batch_op.alter_column('discord_auth_successful',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.false()) # Explicitly set server_default
        batch_op.alter_column('accepted_invite',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.false()) # Explicitly set server_default

    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.alter_column('current_uses',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default=sa.text('0')) # Explicitly set server_default
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.true()) # Explicitly set server_default

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_plex_friend', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('is_discord_bot_whitelisted', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('is_purge_whitelisted', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.alter_column('is_home_user',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.false()) # Explicitly set server_default
        batch_op.alter_column('shares_back',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.false()) # Explicitly set server_default

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('shares_back',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=None) # Revert server_default
        batch_op.alter_column('is_home_user',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=None) # Revert server_default
        batch_op.drop_column('is_purge_whitelisted')
        batch_op.drop_column('is_discord_bot_whitelisted')
        batch_op.drop_column('is_plex_friend')

    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=None) # Revert server_default
        batch_op.alter_column('current_uses',
               existing_type=sa.INTEGER(),
               nullable=True,
               server_default=None) # Revert server_default

    with op.batch_alter_table('invite_usages', schema=None) as batch_op:
        batch_op.alter_column('accepted_invite',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=None) # Revert server_default
        batch_op.alter_column('discord_auth_successful',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=None) # Revert server_default
        batch_op.alter_column('plex_auth_successful',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=None) # Revert server_default
    # ### end Alembic commands ###