"""Add progress columns to stream history

Revision ID: 711dfe122b52
Revises: 3d22fcd04e1b
Create Date: 2025-07-11 15:48:07.823549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711dfe122b52'
down_revision = '3d22fcd04e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_duration_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('view_offset_at_end_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream_history', schema=None) as batch_op:
        batch_op.drop_column('view_offset_at_end_seconds')
        batch_op.drop_column('media_duration_seconds')

    # ### end Alembic commands ###
