"""Add extended Discord details to user and admin models

Revision ID: 96eb712f4b66
Revises: 075ba14cc5a5
Create Date: 2025-06-29 20:39:25.655165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96eb712f4b66'
down_revision = '075ba14cc5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('discord_email_verified', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('discord_email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('discord_email_verified')
        batch_op.drop_column('discord_email')

    with op.batch_alter_table('admin_accounts', schema=None) as batch_op:
        batch_op.drop_column('discord_email_verified')
        batch_op.drop_column('discord_email')

    # ### end Alembic commands ###
