"""Add allow_downloads to Invite model

Revision ID: aecccbce096b
Revises: 4fb2e3be9c82
Create Date: 2025-06-21 17:03:17.343844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression # Add this import at the top of the migration file


# revision identifiers, used by Alembic.
revision = 'aecccbce096b'
down_revision = '4fb2e3be9c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_downloads', sa.Boolean(), 
                                      nullable=False, 
                                      server_default=expression.false())) # <--- MODIFIED HERE

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_column('allow_downloads')

    # ### end Alembic commands ###
