"""Add permissions and password change flag to admin accounts

Revision ID: b5b5ef148efc
Revises: 96eb712f4b66
Create Date: 2025-07-04 12:26:04.298440

"""
from alembic import op
import sqlalchemy as sa

from app.models import JSONEncodedDict

# revision identifiers, used by Alembic.
revision = 'b5b5ef148efc'
down_revision = '96eb712f4b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_password_change', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('permissions', JSONEncodedDict(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_accounts', schema=None) as batch_op:
        batch_op.drop_column('permissions')
        batch_op.drop_column('force_password_change')

    # ### end Alembic commands ###
