"""Add membership_duration_days to Invite model

Revision ID: d2d6805f28ce
Revises: aecccbce096b
Create Date: 2025-06-21 17:50:17.549696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d6805f28ce'
down_revision = 'aecccbce096b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membership_duration_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_expires_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_access_expires_at'), ['access_expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_access_expires_at'))
        batch_op.drop_column('access_expires_at')

    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_column('membership_duration_days')

    # ### end Alembic commands ###
