"""Add role-based access control system

Revision ID: d724af66a06a
Revises: b5b5ef148efc
Create Date: 2025-07-05 13:02:36.455665

"""
from alembic import op
import sqlalchemy as sa

from app.models import JSONEncodedDict

# revision identifiers, used by Alembic.
revision = 'd724af66a06a'
down_revision = 'b5b5ef148efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', JSONEncodedDict(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin_roles',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_accounts.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('admin_id', 'role_id')
    )
    with op.batch_alter_table('admin_accounts', schema=None) as batch_op:
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.TEXT(), nullable=True))

    op.drop_table('admin_roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
